#!/bin/bash

cd 
cd .auto-project-python
python3 create_project.py $1
mkdir $1
mv $1 ~
cd
cd $1 
git init
git remote add origin https://github.com/paulosell/$1.git
touch README.md
git add .
git commit -m "commit inicial"
git push -u origin master
code .